var canvas = document.getElementById("myCanvass");
var ctx = canvas.getContext("2d");
ctx.beginPath();
ctx.arc(90, 75, 50, 0, 2 * Math.PI);
ctx.fillStyle = "violet";
ctx.fill();
ctx.beginPath();
ctx.beginPath();
ctx.globalCompositeOperation = "source-over";
ctx.lineWidth = 2;
ctx.strokeStyle = "#FF0000";
ctx.strokeRect(0, 0, canvas.width, canvas.height);
ctx.arc(210, 75, 50, 0, 2 * Math.PI);
ctx.fillStyle = "violet";
ctx.fill();
ctx.beginPath();
ctx.arc(90, 95, 30, 0, 2 * Math.PI);
ctx.fillStyle = "black";
ctx.fill();
ctx.beginPath();
ctx.arc(210, 95, 30, 0, 2 * Math.PI);
ctx.fillStyle = "black";
ctx.fill();
ctx.beginPath();
ctx.arc(90, 115, 10, 0, 2 * Math.PI);
ctx.fillStyle = "antiquewhite";
ctx.fill();
ctx.beginPath();
ctx.arc(210, 115, 10, 0, 2 * Math.PI);
ctx.fillStyle = "antiquewhite";
ctx.fill();
ctx.beginPath();
ctx.moveTo(150, 100);
ctx.lineTo(100, 200);
ctx.lineTo(200, 200);
ctx.closePath();
ctx.fillStyle = "rebeccapurple";
ctx.fill();